### ISSUE TITLE
4 remaining flags that fail picosvg

### ISSUE THREAD

**Issue by anthrotype** [rsheeter/warp#14]
After we merge #11, #12, #13 and https://github.com/googlefonts/picosvg/pull/204, we are now down to 4 remaining flags that fail to be converted by picosvg and are listed in the `warp_errors.log` after running `python wave_ninja.py --nofail_on_error`. Namely:

```
ERROR /Users/clupo/Github/warp/build_07042021/preflight/third_party/region-flags/svg/TW.svg
returncode 1
stderr
======
Traceback (most recent call last):
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 609, in <module>
    app.run(main)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 538, in main
    svg = load_svg(argv).topicosvg().clip_to_viewbox(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1066, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1076, in topicosvg
    self.shapes_to_paths(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 245, in shapes_to_paths
    for idx, (el, (shape,)) in enumerate(self._elements()):
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 188, in _elements
    elements.append((el, (from_element(el),)))
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 137, in from_element
    args = {
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 138, in <dictcomp>
    f.name: f.type(el.attrib[_attr_name(f.name)])
ValueError: could not convert string to float: '100%'

ERROR /Users/clupo/Github/warp/build_07042021/preflight/third_party/region-flags/svg/BR.svg
returncode 1
stderr
======
Traceback (most recent call last):
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 609, in <module>
    app.run(main)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 538, in main
    svg = load_svg(argv).topicosvg().clip_to_viewbox(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1066, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1076, in topicosvg
    self.shapes_to_paths(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 245, in shapes_to_paths
    for idx, (el, (shape,)) in enumerate(self._elements()):
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 188, in _elements
    elements.append((el, (from_element(el),)))
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 137, in from_element
    args = {
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 138, in <dictcomp>
    f.name: f.type(el.attrib[_attr_name(f.name)])
ValueError: could not convert string to float: '-50%'

ERROR /Users/clupo/Github/warp/build_07042021/preflight/third_party/region-flags/svg/GS.svg
returncode 1
stderr
======
Traceback (most recent call last):
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 609, in <module>
    app.run(main)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 538, in main
    svg = load_svg(argv).topicosvg().clip_to_viewbox(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1066, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1078, in topicosvg
    self.ungroup(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 549, in ungroup
    self._ungroup(self.svg_root)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 486, in _ungroup
    self._inherit_group_attrib(group, child)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 457, in _inherit_group_attrib
    raise ValueError(f"Unable to process group attrib {attrib}")
ValueError: Unable to process group attrib {'font-family': 'Timmons', 'font-size': '14px', 'font-weight': 'bold', 'line-height': '100%'}

ERROR /Users/clupo/Github/warp/build_07042021/preflight/third_party/region-flags/svg/TA.svg
returncode 1
stderr
======
Traceback (most recent call last):
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 609, in <module>
    app.run(main)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/Users/clupo/Github/warp/.venv/lib/python3.9/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/Users/clupo/Github/warp/build_07042021/../naive_warp.py", line 538, in main
    svg = load_svg(argv).topicosvg().clip_to_viewbox(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1066, in topicosvg
    svg.topicosvg(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 1078, in topicosvg
    self.ungroup(inplace=True)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 549, in ungroup
    self._ungroup(self.svg_root)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 486, in _ungroup
    self._inherit_group_attrib(group, child)
  File "/Users/clupo/Github/picosvg/src/picosvg/svg.py", line 457, in _inherit_group_attrib
    raise ValueError(f"Unable to process group attrib {attrib}")
ValueError: Unable to process group attrib {'font-size': '12px'}
```

The GS.svg flag uses an unknown font to set some `<text>`, which is currently unsupported and tricky to support (see https://github.com/googlefonts/nanoemoji/issues/84#issuecomment-815095667).

The TA.svg flag has some `style="font-size:12px"` but they seem to be leftover as the flag does not use any font nor text anywhere so we could simply go and strip those without affecting the result. Yeah, the `flag_preflight.py` script is getting hackier and hackier..

About the other two which fail with the percentage units, it's probably because right now picosvg only handles those for gradients, but unfortunately (for me at least) they can be used almost anywhere, and their meaning, as usual, "depends" on the specific attributes and elements (cf. https://www.w3.org/TR/SVG/coords.html#Units).

**Comment by anthrotype** [comment]
Again -- if we did use resvg/usvg tool to pre-simplify the flags before passing them to picosvg, we would be done already (#10). Usvg among many other things, does support resolving text elements to paths, and also can resolve relative percentages.

**Comment by anthrotype** [comment]
After applying PRs https://github.com/rsheeter/warp/pull/16 and https://github.com/googlefonts/picosvg/pull/205, and an additional commit https://github.com/rsheeter/warp/commit/63c925ed191124be689fa4425161f56186b8e1f2 (from another pending PR https://github.com/rsheeter/warp/pull/12), I can wave all the flags except one, GS.svg, which we can't process because it contains unspported `<text>` elements (https://github.com/googlefonts/nanoemoji/issues/84#issuecomment-815095667).
